#define STB_DXT_IMPLEMENTATION
#define STB_DXT_USE_ROUNDING_BIAS
#include "stb_dxt.h"
#define STB_IMAGE_IMPLEMENTATION
#define STBI_NO_JPEG
#define STBI_NO_PSD
#define STBI_NO_GIF
#define STBI_NO_HDR
#define STBI_NO_PIC
#define STBI_NO_PNM
#include "stb_image.h"
