// SPDX-License-Identifier: GPL-3.0-only

#ifndef INVADER__TAG__HEK__CLASS__ENUM_HPP
#define INVADER__TAG__HEK__CLASS__ENUM_HPP

#include "../../../hek/data_type.hpp"

namespace Invader::HEK {
    enum FramebufferBlendFunction : TagEnum {
        FRAMEBUFFER_BLEND_FUNCTION_ALPHA_BLEND,
        FRAMEBUFFER_BLEND_FUNCTION_MULTIPLY,
        FRAMEBUFFER_BLEND_FUNCTION_DOUBLE_MULTIPLY,
        FRAMEBUFFER_BLEND_FUNCTION_ADD,
        FRAMEBUFFER_BLEND_FUNCTION_SUBTRACT,
        FRAMEBUFFER_BLEND_FUNCTION_COMPONENT_MIN,
        FRAMEBUFFER_BLEND_FUNCTION_COMPONENT_MAX,
        FRAMEBUFFER_BLEND_FUNCTION_ALPHA_MULTIPLY_ADD
    };
};

#endif
